name: Criar pull request ao abrir uma issue

on:
  issues:
    types: [opened]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Create PR branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git checkout -b bugfix/${{ github.event.issue.number }}/${{ github.event.issue.title }}
      
      - name: Create PR file
        run: |
          echo "# Bug Report: ${{ github.event.issue.title }}" > ${{ GITHUB_WORKSPACE }}/${{ github.event.issue.title }}.md
          echo "${{ github.event.issue.body }}" >> ${{ GITHUB_WORKSPACE }}/${{ github.event.issue.title }}.md
          git add .
          git commit -m "Create PR for issue #${{ github.event.issue.number }}"
          git push origin bugfix/${{ github.event.issue.number }}/${{ github.event.issue.title }}
          
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/pulls \
          --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          --header 'content-type: application/json' \
          --data '{
            "title": "[WIP] - Bug Fix for Issue #'${{ github.event.issue.number }}' - '${{ github.event.issue.title }}'",
            "head": "bugfix/'${{ github.event.issue.number }}'/'${{ github.event.issue.title }}'",
            "base": "main",
            "body": "This pull request is automatically created to address issue #"${{ github.event.issue.number }}".\n\nPlease review and merge this pull request when you're ready.\n\n@${{ github.event.issue.user.login }} Please check to make sure that this issue has been fixed as expected."
          }'
