name: Criar pull request ao abrir uma issue

on:
  issues:
    types: [opened]

jobs:
  create-pr:
  runs-on: ubuntu-latest
  steps:
  - name: Criar Pull Request
    uses: peter-evans/create-pull-request@v3.11.0
    with:
      base: nome_da_branch_de_destino
      head: ${{ github.event.issue.user.login }}:nome_da_branch_de_origem
      title: ${{ github.event.issue.title }}
      body: ${{ github.event.issue.body }}